# Generated by Django 3.1.1 on 2020-10-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='documento',
            new_name='document',
        ),
    ]
