# Generated by Django 3.1.1 on 2020-10-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20201005_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='documento',
        ),
        migrations.AddField(
            model_name='contact',
            name='document',
            field=models.FileField(default='', null=True, upload_to='uploads/contact'),
        ),
    ]
