# Generated by Django 3.1.1 on 2020-10-07 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_contact_type_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='data_posted',
            new_name='date_posted',
        ),
    ]
