# Generated by Django 3.1.1 on 2020-10-07 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0001_initial'),
        ('comment', '0008_auto_20201007_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listelement.element'),
        ),
    ]
