# Generated by Django 3.1.1 on 2020-12-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0005_auto_20201127_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='url_clean',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
